[package]
name = "pvs-cluster"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.2.1"
pnet = "0.33.0"
mongodb = "2.4.0"
tokio = "1.27.0"
bson = "2.6.1"